packages:
  - "with-nodejs"
  - "with-bun"
  - "with-python"
  - "with-java"
  - "with-postgres"
  - "with-uv"
  - "with-ruby"
  - "with-web-terminal"
  - "with-opencode"
  - "with-sandbox-agent"
  - "with-dev-server"
  - "with-ttyd"
  - "with-pty"
  - "types/*"
